"use client";

import React, { useState, useMemo } from "react";
import { 
  CheckCircle2, 
  UserCheck, 
  ShieldAlert, 
  Lock, 
  FileText, 
  UploadCloud, 
  CreditCard, 
  RefreshCw, 
  UserX, 
  Gavel, 
  AlertTriangle, 
  ShieldCheck, 
  History,
  Search,
  Scale,
  ShieldX,
  FileSignature,
  ArrowRight,
  ClipboardCheck,
  Link2
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const sectionsData = [
  {
    id: "acceptance-of-terms",
    title: "Acceptance of Terms",
    icon: CheckCircle2,
    content: "Users are required to agree to and accept the terms and conditions before using the technology or service.",
    details: "By accessing or using our services, platform, or products, you agree to be bound by these Terms & Conditions. If you do not agree to all of these terms, do not access or use our services. Your continued use of the platform constitutes your ongoing agreement to any updates or modifications made to these terms."
  },
  {
    id: "user-eligibility",
    title: "User Eligibility",
    icon: UserCheck,
    content: "The terms may specify the eligibility criteria for users, such as age restrictions or geographic limitations.",
    details: "Our services are intended solely for users who are eighteen (18) years of age or older, or the age of majority in your jurisdiction. Any registration, use, or access to the platform by anyone under the specified age is unauthorized, unlicensed, and in violation of these Terms."
  },
  {
    id: "user-responsibilities",
    title: "User Responsibilities",
    icon: ShieldAlert,
    content: "Outline the user’s responsibilities, including compliance with applicable laws, responsible use of the technology, and protection of account credentials.",
    details: "You are solely responsible for maintaining the confidentiality of your account login information and are fully responsible for all activities that occur under your account. You agree to immediately notify us of any unauthorized use or suspected breach of security. You must comply with all applicable local, national, and international laws when using our platforms."
  },
  {
    id: "privacy-policy",
    title: "Privacy Policy",
    icon: Lock,
    content: "Details on how user data is collected, used, and protected, often linking to a separate privacy policy document.",
    details: "Your privacy is of utmost importance to us. Our Privacy Policy governs the collection, use, retention, and protection of your personal information. By using our platform, you acknowledge and agree that your data will be handled in accordance with our Privacy Policy, which is incorporated into these terms by reference."
  },
  {
    id: "intellectual-property-rights",
    title: "Intellectual Property Rights",
    icon: Scale,
    content: "Clarification of the ownership and use of intellectual property, including copyrights, trademarks, and patents.",
    details: "All content, logos, trademarks, graphics, designs, codebase, patentable technology, and other intellectual property assets displayed on or generated by our services are the exclusive property of Mitsafe (Modern Technology) or its licensors. You are granted no rights, title, or interest in our intellectual property except as explicitly stated in these terms."
  },
  {
    id: "license-and-restrictions",
    title: "License and Restrictions",
    icon: FileText,
    content: "Specify the terms of use, including any licenses granted to users and restrictions on how the technology can be used.",
    details: "We grant you a limited, non-exclusive, non-transferable, revocable license to access and use our software services in accordance with these Terms. You may not: (i) copy, modify, or create derivative works of our software; (ii) reverse engineer, decompile, or attempt to extract source code; (iii) bypass security measures; or (iv) resell or distribute our services to third parties without prior written consent."
  },
  {
    id: "user-content",
    title: "User Content",
    icon: UploadCloud,
    content: "Address the use and ownership of content created or uploaded by users on the platform.",
    details: "You retain ownership of any content you upload, submit, or store on our platform. However, by uploading content, you grant us a worldwide, royalty-free, non-exclusive license to host, copy, process, adapt, and transmit that content solely for the purpose of providing and improving our services to you."
  },
  {
    id: "payment-terms",
    title: "Payment Terms",
    icon: CreditCard,
    content: "If applicable, detail the pricing, payment methods, and any other financial terms associated with the use of the technology.",
    details: "Certain services may be subject to subscription fees or one-time payments. You agree to provide current, complete, and accurate billing details. All fees are exclusive of applicable taxes. Failure to pay fees when due may result in immediate suspension or termination of your access to our premium services."
  },
  {
    id: "service-changes-and-discontinuation",
    title: "Service Changes and Discontinuation",
    icon: RefreshCw,
    content: "The right for the provider to make changes to the service, add or remove features, or discontinue the service altogether.",
    details: "We are constantly innovating to provide the best possible experience. We reserve the right to modify, update, suspend, or discontinue any part of our services, features, or products at any time without notice. We shall not be liable to you or any third party for any such modification or discontinuation."
  },
  {
    id: "termination-of-account",
    title: "Termination of Account",
    icon: UserX,
    content: "Circumstances under which the provider can terminate a user’s account, and the process for doing so.",
    details: "We reserve the right to suspend or terminate your account and access to our services at our sole discretion, without notice, for conduct that we believe violates these Terms, violates applicable laws, or is harmful to other users or our business interests."
  },
  {
    id: "dispute-resolution",
    title: "Dispute Resolution",
    icon: Gavel,
    content: "Outline the procedures for resolving disputes, often including clauses related to arbitration and limitations on legal actions.",
    details: "Any dispute, controversy, or claim arising out of or relating to these Terms, including their formation or breach, shall be settled by binding arbitration in accordance with applicable arbitration rules. You agree to waive any right to participate in class action lawsuits or class-wide arbitration."
  },
  {
    id: "limitation-of-liability",
    title: "Limitation of Liability",
    icon: AlertTriangle,
    content: "Specify the extent to which the provider is liable for any damages, and any limitations on that liability.",
    details: "To the maximum extent permitted by law, in no event shall Mitsafe, its directors, employees, or partners, be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses."
  },
  {
    id: "warranty-disclaimer",
    title: "Warranty Disclaimer",
    icon: ShieldX,
    content: "Clarify any warranties or guarantees associated with the technology and disclaimers for certain types of damages.",
    details: "Our services and technology are provided on an 'AS IS' and 'AS AVAILABLE' basis. We disclaim all warranties of any kind, whether express or implied, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, non-infringement, or course of performance."
  },
  {
    id: "security-measures",
    title: "Security Measures",
    icon: ShieldCheck,
    content: "Information on the security measures in place to protect user data and the technology platform.",
    details: "We implement industry-standard administrative, physical, and technical safeguards designed to protect the security, confidentiality, and integrity of your data. However, no security system is impenetrable, and we cannot guarantee 100% security of our platforms."
  },
  {
    id: "updates-to-terms",
    title: "Updates to Terms",
    icon: History,
    content: "The right of the provider to update the terms and conditions, along with the notification process for users.",
    details: "We reserve the right to amend these Terms & Conditions at any time. When we make changes, we will update the date at the top of this page. We encourage you to review this page periodically to stay informed of any updates."
  }
];

export default function TermsClient() {
  const [searchQuery, setSearchQuery] = useState("");
  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Filter sections based on search query
  const filteredSections = useMemo(() => {
    if (!searchQuery.trim()) return sectionsData;
    return sectionsData.filter(
      (sec) =>
        sec.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        sec.content.toLowerCase().includes(searchQuery.toLowerCase()) ||
        sec.details.toLowerCase().includes(searchQuery.toLowerCase())
    );
  }, [searchQuery]);

  const handleCopyLink = (id: string) => {
    const url = `${window.location.origin}${window.location.pathname}#${id}`;
    navigator.clipboard.writeText(url);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleScrollTo = (id: string) => {
    const el = document.getElementById(id);
    if (el) {
      el.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  return (
    <div className="bg-slate-50 min-h-screen text-slate-800 selection:bg-[#2563EB]/10 selection:text-[#2563EB] pt-32 pb-24 relative overflow-hidden">
      {/* Decorative Background Elements */}
      <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-blue-100/40 rounded-full blur-3xl -z-10 pointer-events-none" />
      <div className="absolute bottom-10 right-1/4 w-[600px] h-[600px] bg-purple-100/30 rounded-full blur-3xl -z-10 pointer-events-none" />

      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        
        {/* Header Hero Area */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-blue-50 border border-blue-200/50 text-blue-600 text-xs font-bold uppercase tracking-wider mb-5"
          >
            <FileSignature className="w-3.5 h-3.5" />
            Legal Agreement
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="text-4xl sm:text-5xl font-black text-slate-900 tracking-tight leading-none mb-6 font-display"
          >
            Terms &amp; Conditions
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="text-slate-600 text-base sm:text-lg font-medium leading-relaxed"
          >
            The Terms &amp; Conditions (T&amp;C) for modern technology vary based on the specific service, platform, or product offered. Below is a comprehensive overview of the core elements governing our engagement.
          </motion.p>
        </div>

        {/* Search & Main Layout Section */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Left Sidebar Menu (Table of Contents) */}
          <motion.div 
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
            className="lg:col-span-4 lg:sticky lg:top-28 bg-white border border-slate-200/80 rounded-3xl p-6 shadow-sm hidden lg:block"
          >
            <h3 className="text-slate-900 font-extrabold text-sm uppercase tracking-wider mb-4">
              On This Page
            </h3>
            
            <div className="h-[450px] overflow-y-auto pr-2 space-y-1 custom-scrollbar">
              {sectionsData.map((sec) => (
                <button
                  key={sec.id}
                  onClick={() => handleScrollTo(sec.id)}
                  className="w-full text-left px-3.5 py-2.5 rounded-xl text-[13px] font-semibold text-slate-600 hover:bg-slate-50 hover:text-blue-600 transition-all flex items-center gap-3 border border-transparent hover:border-slate-100"
                >
                  <sec.icon className="w-4 h-4 shrink-0 text-slate-400 group-hover:text-blue-600" />
                  <span className="truncate">{sec.title}</span>
                </button>
              ))}
            </div>

            <div className="pt-5 mt-5 border-t border-slate-100 flex flex-col gap-3">
              <div className="text-[11px] font-medium text-slate-500">
                Last updated: July 24, 2026
              </div>
              <div className="text-[11px] font-bold text-slate-900">
                © 2021 — Ewebot b
              </div>
            </div>
          </motion.div>

          {/* Right Main Content Area */}
          <div className="lg:col-span-8 space-y-6">
            
            {/* Search Input Card */}
            <motion.div
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="bg-white border border-slate-200/80 rounded-3xl p-5 shadow-xs flex items-center gap-4"
            >
              <div className="relative flex-grow">
                <Search className="w-5 h-5 text-slate-400 absolute left-4 top-1/2 -translate-y-1/2" />
                <input
                  type="text"
                  placeholder="Search legal terms or sections..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full pl-12 pr-4 py-3 rounded-2xl bg-slate-50 border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 text-sm font-semibold transition-all"
                />
              </div>
            </motion.div>

            {/* Sections Content List */}
            <div className="space-y-6">
              <AnimatePresence mode="popLayout">
                {filteredSections.map((sec, idx) => {
                  const Icon = sec.icon;
                  return (
                    <motion.div
                      key={sec.id}
                      id={sec.id}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, scale: 0.95 }}
                      transition={{ duration: 0.4, delay: Math.min(idx * 0.05, 0.3) }}
                      className="bg-white border border-slate-200/80 rounded-3xl p-6 sm:p-8 shadow-xs hover:shadow-md hover:border-slate-300 transition-all duration-300 relative group scroll-mt-24"
                    >
                      {/* Top Action Panel */}
                      <div className="flex items-start justify-between gap-4 mb-4">
                        <div className="flex items-center gap-4">
                          <div className="w-12 h-12 rounded-2xl bg-blue-50 text-blue-600 border border-blue-100 flex items-center justify-center shrink-0">
                            <Icon className="w-6 h-6" />
                          </div>
                          <div>
                            <h2 className="text-xl font-extrabold text-slate-900 tracking-tight">
                              {sec.title}
                            </h2>
                            <span className="text-[11px] font-bold text-blue-500 uppercase tracking-wider">
                              Section {idx + 1}
                            </span>
                          </div>
                        </div>

                        {/* Copy Link Button */}
                        <button
                          onClick={() => handleCopyLink(sec.id)}
                          className="w-9 h-9 rounded-xl border border-slate-200 hover:border-slate-300 hover:bg-slate-50 flex items-center justify-center transition-all text-slate-400 hover:text-slate-700"
                          title="Copy Link to Section"
                        >
                          {copiedId === sec.id ? (
                            <ClipboardCheck className="w-4 h-4 text-green-600 animate-in fade-in zoom-in-75 duration-200" />
                          ) : (
                            <Link2 className="w-4 h-4" />
                          )}
                        </button>
                      </div>

                      {/* Content Overview */}
                      <p className="text-slate-800 text-sm sm:text-base font-bold leading-relaxed mb-3">
                        {sec.content}
                      </p>

                      {/* Detailed Content */}
                      <div className="text-slate-600 text-xs sm:text-sm leading-relaxed font-medium bg-slate-50 border border-slate-100 rounded-2xl p-4 sm:p-5 mt-4">
                        {sec.details}
                      </div>
                    </motion.div>
                  );
                })}
              </AnimatePresence>

              {/* No Results Fallback */}
              {filteredSections.length === 0 && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="bg-white border border-slate-200 rounded-3xl p-12 text-center"
                >
                  <p className="text-slate-500 text-sm font-semibold">
                    No matching sections found for "{searchQuery}".
                  </p>
                </motion.div>
              )}
            </div>

            {/* Mobile Footer Meta */}
            <div className="lg:hidden bg-white border border-slate-200/80 rounded-3xl p-6 text-center space-y-2">
              <div className="text-xs font-semibold text-slate-500">
                Last updated: July 24, 2026
              </div>
              <div className="text-xs font-bold text-slate-900">
                © 2021 — Ewebot b
              </div>
            </div>

          </div>

        </div>

      </div>
    </div>
  );
}
